CREATE TABLE TDEPT
     (DEPTNO   CHAR(3)     NOT NULL,
      DEPTNAME VARCHAR(36) NOT NULL,
      MGRNO    CHAR(6),
      ADMRDEPT CHAR(3)     NOT NULL,
      PRIMARY KEY(DEPTNO))
-- example insert
INSERT INTO TDEPT VALUES ('D10', 'ACCOUNTING', 'E17', 'D20');
INSERT INTO TDEPT VALUES ('D20', 'RESEARCH', 'E15', 'D20');
INSERT INTO TDEPT VALUES ('D30', 'SALES', 'E11', 'D20');